### ISSUE TITLE
NiftiException error

### ISSUE THREAD

**Issue by grandjeanlab** [IBT-FMI/SAMRI#101]
Trying to run the diagnostic function together with the test dataset provided. 
I get the following error. Any idea why?

Standard error:
terminate called after throwing an instance of 'NiftiException'
  what():  Error: cant open file /home/gjoanes/Desktop/BIDS_test/diagnostic_work/_path_..home..gjoanes..Desktop..BIDS_test..bids..sub-6553..ses-ofMk..func..sub-6553_ses-ofMk_task-CogBr_acq-EPI_run-0_cbv.gz/slicetimer/forced_dummy_scans_file_st.nii.gz
Aborted (core dumped)
Return code: 134

190929-13:02:40,422 nipype.workflow INFO:
	 [MultiProc] Running 0 tasks, and 0 jobs ready. Free memory (GB): 13.85/13.85, Free processors: 6/6.
190929-13:02:42,419 nipype.workflow INFO:
	 ***********************************
190929-13:02:42,419 nipype.workflow ERROR:
	 could not run node: diagnostic_work.slicetimer.a0
190929-13:02:42,419 nipype.workflow INFO:
	 crashfile: /home/gjoanes/Desktop/BIDS_test/diagnostic_crashdump/crash-20190929-130238-gjoanes-slicetimer.a0-3ceacf48-cbea-4a3c-9556-9bc640831491.pklz
190929-13:02:42,419 nipype.workflow ERROR:
	 could not run node: diagnostic_work.slicetimer.a1
190929-13:02:42,419 nipype.workflow INFO:
	 crashfile: /home/gjoanes/Desktop/BIDS_test/diagnostic_crashdump/crash-20190929-130240-gjoanes-slicetimer.a1-3d75ae31-94d4-4466-a65b-18b8a3dea4f3.pklz
190929-13:02:42,419 nipype.workflow INFO:
	 ***********************************

**Comment by TheChymera** [comment]
can you please post the output of 

```
nipypecli crash /home/gjoanes/Desktop/BIDS_test/diagnostic_crashdump/crash-20190929-130240-gjoanes-slicetimer.a1-3d75ae31-94d4-4466-a65b-18b8a3dea4f3.pklz
```

and upload the `/home/gjoanes/Desktop/BIDS_test/diagnostic_work/path..home..gjoanes..Desktop..BIDS_test..bids..sub-6553..ses-ofMk..func..sub-6553_ses-ofMk_task-CogBr_acq-EPI_run-0_cbv.gz/slicetimer/forced_dummy_scans_file_st.nii.gz` file somewhere?
