### ISSUE TITLE
advice on installing SAMRI without breaking existing dependencies

### ISSUE THREAD

**Issue by andrewcyung** [IBT-FMI/SAMRI#105]
Hi there,

I am really interested in using SAMRI to assist in animal fMRI data processing, and have noticed that SAMRI uses some of the dependencies that we are already using (most notably nipype, fsl, ants, and nibabel).  There are some custom configurations to these external packages that I made for my own data processing, and so I was wondering if SAMRI installation will overwrite or update any of my dependencies.  I see on the readme that you recommend using the gentoo package via the ./install.sh script.  Does this make a local user copy of the the SAMRI files, plus all of its dependencies?

Any advice you can give me would be greatly appreciated, to figuring out a "safe" way to install SAMRI without breaking up existing dependencies.  Thanks!

**Comment by TheChymera** [comment]
Hi, SAMRI just contains the top-level analysis code. It uses whatever versions of the dependencies are available on your system, and does not itself install or modify them. There is no unsafe way of installing SAMRI, but you will have to install the dependencies somehow. This is usually done via your distribution's package manager, and if you use Gentoo Linux, you can install both SAMRI and its dependencies automatically with `emerge samri`, after you've enabled [the Science Overlay](https://github.com/gentoo/sci).
