### ISSUE TITLE
mouse-brain-atlases-0.5.3.tar.xz missing?

### ISSUE THREAD

**Issue by stebo85** [IBT-FMI/SAMRI#112]
Dear @TheChymera 

I am trying to emerge samri, but run into this problem:
>>> Emerging (5 of 288) sci-biology/mouse-brain-atlases-0.5.3::science
Unable to unshare: EPERM (for FEATURES="ipc-sandbox network-sandbox pid-sandbox")
>>> Downloading 'http://distfiles.gentoo.org/distfiles/71/mouse-brain-atlases-0.5.3.tar.xz'
--2020-12-07 10:17:38--  http://distfiles.gentoo.org/distfiles/71/mouse-brain-atlases-0.5.3.tar.xz
Resolving distfiles.gentoo.org... 64.50.236.52, 64.50.233.100, 140.211.166.134, ...
Connecting to distfiles.gentoo.org|64.50.236.52|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-12-07 10:17:38 ERROR 404: Not Found.

>>> Downloading 'http://chymera.eu/distfiles/mouse-brain-atlases-0.5.3.tar.xz'
--2020-12-07 10:17:38--  http://chymera.eu/distfiles/mouse-brain-atlases-0.5.3.tar.xz
Resolving chymera.eu... 173.236.183.125
Connecting to chymera.eu|173.236.183.125|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-12-07 10:17:39 ERROR 404: Not Found.

is there anything wrong on my side or is the file really not available?

Cheers
Steffen

**Comment by TheChymera** [comment]
I messed up the distfiles, apparently. I am reuploading this (and dozens of other archives) from the backups now :)
If you have a personal server on which we could host a mirror, that would be great! :) If not, this really shouldn't happen. The server is really stable, just that I somehow managed to delete old data in the directory when running `rsync` to add a new archive. (Rat brain data atlases, btw ^^  http://chymera.eu/distfiles/rat-brain-atlases-0.1.tar.xz)

**Comment by TheChymera** [comment]
@stebo85 ok, should work now! Let me know if that's ok.

**Comment by stebo85** [comment]
@TheChymera - great - I now got past this step :) 

my next problem is that I am hitting the time limit in github actions to build the software - Is there a trick to build samri in less then than 6 hours?
https://github.com/NeuroDesk/caid/runs/1514228250?check_suite_focus=true

**Comment by TheChymera** [comment]
@stebo85 SAMRI itself should be installed pretty much instantly. I assume this is the SAMRI dependency stack you are talking about. I highly doubt FSL+ANTS+AFNI+NumPy+SciPy can be built in under 6 hours :(

Could you go into greater detail regarding what exactly you're trying to do? It's possible tried to do something similar before as well — in order to auto-run the test suite.

**Comment by stebo85** [comment]
@TheChymera ok, this makes sense. I am trying to integrate samri in our neurodesk  project where we make a variety of neuroimaging tools available in singularity containers to allow users to easily run them on different hpc platforms and not having to install them manually :) we build these images with github actions and are therefore Limited to 6 hours runtime. Do you have by any chance a docker container with the dependencies of samri already built?

**Comment by TheChymera** [comment]
@stebo85 not really, we gave up on containers because the entire architecture is pretty bad for source-based installs. What we wanted to do instead for the test suite, is to create a tarball image of the system, and just start it in chroot. It's basically like a container, but without a lot of the overhead. You can see how we do it for the StereotaXYZ package here: https://github.com/IBT-FMI/StereotaXYZ/blob/master/.travis.yml

If you find that usable, I could finish generating an analogous tarball for SAMRI.

Lastly, SAMRI does not necessarily require Gentoo and source-based installation. That's just what we use in order to ensure system reproducibility, get proper control over the dependencies, and make sure we can automatically access all dependencies we need. It could work on any other distro just as well, just that none of our collaborators use other distros. If you want, you could generate a docker image, based on whatever OS you want, simply by satisfying the dependency relationships (full list here: https://github.com/IBT-FMI/SAMRI/blob/master/.gentoo/sci-biology/samri/samri-99999.ebuild ). I'd be happy to help out if you run into any issues. Particularly, some packages might not be automatically available for other distributions. The mouse-brain-atlases package you can get from here https://github.com/IBT-FMI/mouse-brain-atlases_generator#mouse-brain-atlases-package-releases

**Comment by stebo85** [comment]
@TheChymera - ok, I tried setting it all up in a ubuntu container and got pretty far :) 

I run into a problem when installing the mouse-brain-atlases_generator:
./make_archives.sh -v 0.5 -m

```
Reading /opt/mouse-brain-atlases_generator/mouse-brain-atlases-0.5/abi_10micron_annotation.nrrd
Converting /opt/mouse-brain-atlases_generator/mouse-brain-atlases-0.5/abi_10micron_annotation.nrrd
Reading /opt/mouse-brain-atlases_generator/mouse-brain-atlases-0.5/abi_10micron_average.nrrd
Converting /opt/mouse-brain-atlases_generator/mouse-brain-atlases-0.5/abi_10micron_average.nrrd
terminate called after throwing an instance of 'std::invalid_argument'
  what():  stoi
../abi2dsurqec_40micron.sh: line 4:   742 Aborted                 ResampleImage 3 abi_10micron_average.nii abi_15micron_average.nii 0.015x0.015x0.015 size=1 spacing=0 4
Image Exception : #63 :: No image files match: abi_15micron_average
terminate called after throwing an instance of 'std::runtime_error'
  what():  No image files match: abi_15micron_average
../abi2dsurqec_40micron.sh: line 5:   751 Aborted                 fslorient -copyqform2sform abi_15micron_average.nii
terminate called after throwing an instance of 'std::invalid_argument'
  what():  stoi
../abi2dsurqec_40micron.sh: line 6:   752 Aborted                 ResampleImage 3 abi_10micron_average.nii abi_40micron_average.nii 0.04x0.04x0.04 size=1 spacing=0 4
Image Exception : #63 :: No image files match: abi_40micron_average
terminate called after throwing an instance of 'std::runtime_error'
  what():  No image files match: abi_40micron_average
../abi2dsurqec_40micron.sh: line 7:   761 Aborted                 fslorient -copyqform2sform abi_40micron_average.nii
terminate called after throwing an instance of 'std::invalid_argument'
  what():  stoi
../abi2dsurqec_40micron.sh: line 8:   762 Aborted                 ResampleImage 3 abi_10micron_average.nii abi_200micron_average.nii 0.2x0.2x0.2 size=1 spacing=0 4
Image Exception : #63 :: No image files match: abi_200micron_average
terminate called after throwing an instance of 'std::runtime_error'
  what():  No image files match: abi_200micron_average
../abi2dsurqec_40micron.sh: line 9:   771 Aborted                 fslorient -copyqform2sform abi_200micron_average.nii
 file abi_15micron_average.nii does not exist . 
../abi2dsurqec_40micron.sh: line 12:   772 Segmentation fault      antsApplyTransforms -d 3 -e 0 -i abi_10micron_annotation.nii -r abi_15micron_average.nii -o abi_15micron_annotation.nii -n MultiLabel -t Identity
Image Exception : #63 :: No image files match: abi_15micron_annotation
terminate called after throwing an instance of 'std::runtime_error'
  what():  No image files match: abi_15micron_annotation
../abi2dsurqec_40micron.sh: line 13:   781 Aborted                 fslorient -copyqform2sform abi_15micron_annotation.nii
 file abi_40micron_average.nii does not exist . 
../abi2dsurqec_40micron.sh: line 14:   782 Segmentation fault      antsApplyTransforms -d 3 -e 0 -i abi_10micron_annotation.nii -r abi_40micron_average.nii -o abi_40micron_annotation.nii -n MultiLabel -t Identity
Image Exception : #63 :: No image files match: abi_40micron_annotation
terminate called after throwing an instance of 'std::runtime_error'
  what():  No image files match: abi_40micron_annotation
../abi2dsurqec_40micron.sh: line 15:   791 Aborted                 fslorient -copyqform2sform abi_40micron_annotation.nii
All_Command_lines_OK
Using single precision for computations.
 file abi_40micron_average.nii does not exist . 
Exception Object caught: 

itk::ExceptionObject (0x3d66920)
Location: "unknown"
File: /src/ants/build/staging/include/ITK-5.1/itkCenteredTransformInitializer.hxx
Line: 45
Description: itk::ERROR: CenteredTransformInitializer(0x3d63fc0): Moving Image has not been set


Image Exception : #63 :: No image files match: abi2dsurqec_40micron_masked
terminate called after throwing an instance of 'std::runtime_error'
  what():  No image files match: abi2dsurqec_40micron_masked
../abi2dsurqec_40micron.sh: line 52:   801 Aborted                 fslorient -copyqform2sform abi2dsurqec_40micron_masked.nii
Transform file does not exist: abi2dsurqec_Composite.h5
Image Exception : #63 :: No image files match: abi2dsurqec_40_annotation
terminate called after throwing an instance of 'std::runtime_error'
  what():  No image files match: abi2dsurqec_40_annotation
../abi2dsurqec_40micron.sh: line 57:   811 Aborted                 fslorient -copyqform2sform abi2dsurqec_40_annotation.nii
rm: cannot remove 'abi2dsurqec_InverseComposite.h5': No such file or directory
```

**Comment by TheChymera** [comment]
@stebo85 sorry, apparently my instructions were unclear.

What you have tried to do is *regenerate* the mouse-brain-atlases package. That should also work, but it's not necessary, and it might not give you the actual version which we and other people use. The versioned release can be downloaded from the link in the README. 

Let me know if you have any suggestions on how to make this clearer.

**Comment by TheChymera** [comment]
Closing due to lack of feedback :( @stebo85 please feel free to reopen :)
