### ISSUE TITLE
is "samri_bindata-0.1.2.tar.xz" missing?

### ISSUE THREAD

**Issue by ChariteExpMri** [IBT-FMI/SAMRI#114]
Dear @TheChymera,
when I try to download the **samri_bindata-0.1.2.tar.xz** -testdata via
wget http://chymera.eu/distfiles/samri_bindata-0.1.2.tar.xz
I receive the following 404-error:
```
_--2021-09-28 10:40:03--  http://chymera.eu/distfiles/samri_bindata-0.1.2.tar.xz
Auflösen des Hostnamens chymera.eu (chymera.eu)… 173.236.183.125
Verbindungsaufbau zu chymera.eu (chymera.eu)|173.236.183.125|:80 … verbunden.
HTTP-Anforderung gesendet, auf Antwort wird gewartet … 404 Not Found
2021-09-28 10:40:03 FEHLER 404: Not Found._
```
Is the data set still available?
Thank you,
Paul Koch

**Comment by TheChymera** [comment]
@ChariteExpMri we use a newer archive with better curated data now: http://chymera.eu/distfiles/samri_bindata-0.4.tar.xz Apparenly I had forgotten to update the links in the README wget commands, should be fixed now as per  https://github.com/IBT-FMI/SAMRI/commit/5a3cacbb1df1ccadc3696866b4473651dec00cf3 :)

**Comment by ChariteExpMri** [comment]
Thank you very much, it works now!
