### ISSUE TITLE
Dynamic/Functional Connectivity

### ISSUE THREAD

**Issue by damaggu** [IBT-FMI/SAMRI#16]
Implementation of F.C. as an additional feature of SAMRI

**Comment by TheChymera** [comment]
I got ready to start building on your outline module just now, this included:

* moving the plotting function to the appropriate module 2e4152a8e064990a4ef05ddb044509f8373cb408
* renaming the submodule to something more descriptive (analogously, we call our GLM submodule `glm.py` and not `stimulus_evoked.py`; something we have previously talked about, and which seemed very hot indeed at ISMRM 2017 was using functional connectivity in stimulus-evoked paradigms). 29386d28b03572ea5d1f53b39eb3d16db18d4890 d5c6951299e0ae62e30bf3168d6a369b650503d4

**Comment by TheChymera** [comment]
Seed based connectivity available as of b51602d7b1290c1ec2a68841c646bf88751568d7 .

**Comment by damaggu** [comment]
Functional Connectivity Matrix plot, atlas based, available as of 7159a25b03368a268cc5001b9f65c70ca6fe5b79 .

**Comment by TheChymera** [comment]
Closing for now.
