### ISSUE TITLE
Cannot output mutliple fMRI "runs" since new update 

### ISSUE THREAD

**Issue by grandjeanlab** [IBT-FMI/SAMRI#72]
I have a scan protocol with multiple fmri. Since last update to allow only structural img export, the following command doesn't work any more

SAMRI bru2bids -o .  -f '{"acquisition":["EPI1","EPI2","EPI3"]}' -s '{acquisition":["RARE"]} raw

scan are named as follow. 

acq-RARE_T2w
task-SSFO_acq-EPI1_bold
task-rest_acq-EPI2_bold
task-SSFO_acq-EPI3_bold

While the individual exports do
SAMRI bru2bids -o .  -f '{"acquisition":["EPI1"]}' -s '{acquisition":["RARE"]} raw

**Comment by TheChymera** [comment]
@joanesg can you upload an example dataset? Also, in what way does it fail? Does it crash, produce the wrong files, or produce only some of the files you wanted?

**Comment by grandjeanlab** [comment]
This has been seemingly resolved in the new update.
