### ISSUE TITLE
stat3D with `pos_values=True` sets the color for negative values to a sub-threshold positive value.

### ISSUE THREAD

**Issue by TheChymera** [IBT-FMI/SAMRI#90]
With the following code I get the picture below:

```
import samri.plotting.maps as maps
import matplotlib.pyplot as plt

stat_map = "map.nii.gz"
template = "/usr/share/mouse-brain-atlases/dsurqec_40micron_masked.nii"

maps.stat3D(stat_map,
	cut_coords=(0.5,-3.2,-4.5),
	scale=0.3,
	template=template,
	show_plot=False,
	threshold=3,
	threshold_mesh=3,
	pos_values=True,
	)
```

![test](https://user-images.githubusercontent.com/950524/54012769-61d87480-4177-11e9-8ba2-3c13bb112017.png)

Please also refer to this [minimal reproducible example](http://chymera.eu/debug/samri/3dplot.tar.xz).

**Comment by setina42** [comment]
Please see PR #91 
Do you think we should add the option for plotting only negative values as well?

**Comment by TheChymera** [comment]
Yes, and I would rename it `positive_only` and name the other `negative_only`, more explicit names are better :)
