### ISSUE TITLE
ANTs with or without GUI ?

### ISSUE THREAD

**Issue by samfux84** [IBT-FMI/SAMRI#96]
Hi,

ANTs is listed as a dependency of SAMRI. Does ANTs need to be built with the GUI (QT and VTK) or can SAMRI also use ANTs without GUI ?

Best regards

Sam

**Comment by TheChymera** [comment]
No, the GUI is not required for the SAMRI workflows to be able to access ANTs. It's all done via the command line interface.

**Comment by samfux84** [comment]
Thank you for the reply.
